### ISSUE TITLE
如果我只想要type类型

### ISSUE THREAD

**Issue by JYNJBN** [openapi-ui/openapi-ts-request#102]
大佬，请问，如果我只想要type类型，要怎么操作？

**Comment by JYNJBN** [comment]
大佬，请问，如果我只想要type类型的文件，不需要其他文件，要怎么操作？

**Comment by rookie-luochao** [comment]
目前是默认生成了types 和 axios 客户端，你是想只生成 types 吗？

**Comment by rookie-luochao** [comment]
你没回复我，也不知道你还需不需要这个功能，但是我支持了你的功能诉求：仅生成 typescript type 的功能

详情见：[v0.12.0](https://github.com/openapi-ui/openapi-ts-request/releases/tag/v0.12.0)
