### ISSUE TITLE
枚举类型名称为数字时生成的ts有bug. 

### ISSUE THREAD

**Issue by EPZ1016** [openapi-ui/openapi-ts-request#117]
简单看了一下,貌似有全number时候的判断,但是没起效的样子
![image](https://github.com/user-attachments/assets/26b9858a-b5fa-4ea8-9b15-bb164fdc20c8)
![image](https://github.com/user-attachments/assets/3b3eb510-d8bb-4206-bd44-bb8240f6eff2)
这里我修改了一下, 效果如下
![1732456715445](https://github.com/user-attachments/assets/ec80772e-250f-4726-bd4d-72df18bb1c30)
![1732456748245](https://github.com/user-attachments/assets/8a177bb4-7201-4a75-b441-1fef41a1a436)

**Comment by rookie-luochao** [comment]
如果修复好了，可以提一个pr，我合并一下，数字枚举我修了2次了，竟然还有问题😭

**Comment by rookie-luochao** [comment]
数字枚举的代码在这里 https://github.com/openapi-ui/openapi-ts-request/blob/main/src/generator/serviceGenarator.ts#L1071

**Comment by EPZ1016** [comment]
这么快....你这是随时在线的么, 我没那么热心的其实. 这次是失业在家带娃太久了....心血来潮...提了一下...明后天吧有时间我研究一下

> 如果修复好了，可以提一个pr，我合并一下，数字枚举我修了2次了，竟然还有问题😭

**Comment by rookie-luochao** [comment]
> 这么快....你这是随时在线的么, 我没那么热心的其实. 这次是失业在家带娃太久了....心血来潮...提了一下...明后天吧有时间我研究一下
> 
> > 如果修复好了，可以提一个pr，我合并一下，数字枚举我修了2次了，竟然还有问题😭

现在这年头，估计都卷得很，只有更卷才能有份工作，太难了

**Comment by rookie-luochao** [comment]
大佬，请问有时间针对你的问题提个pr吗？

**Comment by lezzhao** [comment]
这个应该是负数没有处理到吧
