### ISSUE TITLE
type.ts文件中的注释生成

### ISSUE THREAD

**Issue by jianjian584** [openapi-ui/openapi-ts-request#146]
type.ts中的泛型生成  只保留了对象类型中内变量的注释生成  schemas中的description全部忽略了  用到诸如数字表状态的枚举类型会变成XXX[0] = ”0“  没有可读性

**Comment by rookie-luochao** [comment]
> type.ts中的泛型生成 只保留了对象类型中内变量的注释生成 schemas中的description全部忽略了 用到诸如数字表状态的枚举类型会变成XXX[0] = ”0“ 没有可读性

阅读了你的描述，有点没看懂细节，方便加vx: 1055120207 详细交流bug？

**Comment by rookie-luochao** [comment]
已暂时找到可行方案，我先关闭issue了哈，有问题我们再交流
