### ISSUE TITLE
[BUG]  缺少依赖导致的格式化失败

### ISSUE THREAD

**Issue by zhao-coder123** [openapi-ui/openapi-ts-request#15]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Steps To Reproduce

![image](https://github.com/openapi-ui/openapi-ts-request/assets/135207263/57a1540a-a3ed-4a40-a3a0-5f9112351454)

### Environment

```markdown
- OS:Mac
```

### Additional context

将依赖更改到 dependencies下就好了

**Comment by rookie-luochao** [comment]
原来一直格式化失败是因为这个

**Comment by rookie-luochao** [comment]
good job, 关联pr #16
