### ISSUE TITLE
为什么不把类型放在一个全局的命名空间下了？之前这个设计挺好的，全局可以使用

### ISSUE THREAD

**Issue by GreatAuk** [openapi-ui/openapi-ts-request#17]

**Comment by rookie-luochao** [comment]
对于ast不友好，请问现在这样有什么问题吗？现在也暴露给你API，只是你需要引用一下而已 import * from "apis/types.ts"

**Comment by rookie-luochao** [comment]
还有一点是用全局命名空间，重名的type, 你引用起来会有问题

**Comment by rookie-luochao** [comment]
现在你要用到哪个 type, 直接输入名字的部分字母，ast会提示你引用路径？

**Comment by rookie-luochao** [comment]
全局命名空间，里面的枚举无法使用等等问题，是出于很多方面考虑不用 namespace 会更好

**Comment by GreatAuk** [comment]
用习惯了吧

**Comment by rookie-luochao** [comment]
> 用习惯了吧

就是用习惯了，而且在低版本的 ts 中，namespace 需要借助 /// <reference types="type.d.ts" /> ，以前我在一个低ts版本中死活不提示 namespace，后面加了这个 reference 才可以，欢迎反馈
