### ISSUE TITLE
[文档] Readme中的config名称有问题

### ISSUE THREAD

**Issue by 1379255913** [openapi-ui/openapi-ts-request#32]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

文档中要求配置名称为openapi-ts.config.ts，但是代码中实现的获取配置为openapi-ts-request.config.ts

### Expected Behavior

符合文档或者修改文档

### Steps To Reproduce

-

### Environment

```markdown
- OS:
```

**Comment by rookie-luochao** [comment]
等会就修改，我以前也没开发过npx的命令，原先的openapi-ts-request命令和npm包重命，导致npx openapi-ts-request + bin 永远都不会执行，只能执行这个openapi-ts-request，被迫修改命令改漏了😢

**Comment by rookie-luochao** [comment]
还是倾向于修改文档，你要不要提个pr

**Comment by rookie-luochao** [comment]
已修复 https://github.com/openapi-ui/openapi-ts-request/commit/01ca65ed32bfeed12c3b28722b7e1db0904fefef

**Comment by rookie-luochao** [comment]
请问还有问题吗？

**Comment by 1379255913** [comment]
目前没有问题了

**Comment by rookie-luochao** [comment]
好的，谢谢哈，欢迎提改进意见😁😁😁
