### ISSUE TITLE
[BUG] 无类型声明文件

### ISSUE THREAD

**Issue by nigiwen** [openapi-ui/openapi-ts-request#4]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

导入模块后 ts 报错

### Steps To Reproduce

```ts
import { generateService } from 'openapi-ts-request'
```
> 无法找到模块“openapi-ts-request”的声明文件。“E:/demo-openapi/node_modules/.pnpm/openapi-ts-request@0.1.1_chokidar@3.6.0_typescript@5.5.2/node_modules/openapi-ts-request/dist/index.js”隐式拥有 "any" 类型。
  尝试使用 `npm i --save-dev @types/openapi-ts-request` (如果存在)，或者添加一个包含 `declare module 'openapi-ts-request';` 的新声明(.d.ts)文件ts(7016)

### Environment

```markdown
- OS:win
```

**Comment by rookie-luochao** [comment]
不需要@types/openapi-ts-request 包，是我types目录手滑写错了

**Comment by rookie-luochao** [comment]
ts类型声明文件已添加，import已经不会报ts类型错误

**Comment by rookie-luochao** [comment]
你拉取下最新的包试试哈
