### ISSUE TITLE
[BUG]  API 中存在数组对象时生成代码存在问题

### ISSUE THREAD

**Issue by normal-coder** [openapi-ui/openapi-ts-request#49]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

当 API 中存在数组对象时生成代码存在问题，将导致生成代码无法被正常调用。

如：`output` 是作为 formData 参数名，但其内容实际上是一个对象/数组，在正常的 Swagger 中生成如下：

<img width="709" alt="image" src="https://github.com/user-attachments/assets/c1fd4c07-b54a-4c1d-80f2-5e708e412d5a">

当前生成代码效果为：

```typescript
completed_at?: string,
/** 标题 */
output[title]: string,
/** 概论 */
output[summary]: string,
/** 详细信息 */
output[text]?: string,
/** 路径 */
output[annotations][path]: string[],
/** 开始行 */
output[annotations][start_line]: number[],
/** 结束行 */
output[annotations][end_line]: number[],
/** 开始列 */
output[annotations][start_column]?: number[],
/** 结束列 */
output[annotations][end_column]?: number[],
```

预期应该生成：
```typescript
/** 标题 */
'output[title]': string,
/** 概论 */
'output[summary]': string,
/** 详细信息 */
'output[text]'?: string,
/** 路径 */
'output[annotations][path]': string[],
/** 开始行 */
'output[annotations][start_line]': number[],
/** 结束行 */
'output[annotations][end_line]': number[],
```

错误的生成会导致工程中 `output` 出现重复而导致 **Confusing "duplicate identifier" ts(2300)** 错误

### Expected Behavior

-

### Steps To Reproduce

参考上方复现环境

### Environment

```markdown
该问题与操作系统无关
```

### Additional context

 none.

**Comment by rookie-luochao** [comment]
已经在 #50 pr中修复
