### ISSUE TITLE
[BUG] 无法正确转换

### ISSUE THREAD

**Issue by nigiwen** [openapi-ui/openapi-ts-request#5]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Steps To Reproduce

![image](https://github.com/openapi-ui/openapi-ts-request/assets/67454874/619a688d-4c7c-492e-a44e-cdaa9a7c55f5)

### Environment

```markdown
- OS:win
```

**Comment by rookie-luochao** [comment]
除开类型提示，功能可以正常使用不

**Comment by nigiwen** [comment]
貌似ts代码格式有点问题

**Comment by rookie-luochao** [comment]
所以说用import功能也是可以正常使用的吧，我没有测试import，只测试了require

**Comment by nigiwen** [comment]
晚会吧我现在用的手机回的，import是正常的

**Comment by rookie-luochao** [comment]
好的，谢谢哈，功能应该是正常的，只是我粗心类型路径写错了

**Comment by nigiwen** [comment]
### 为啥会格式化失败

![image](https://github.com/openapi-ui/openapi-ts-request/assets/67454874/8dcbe216-9aae-4f71-99fd-831cbed9ef49)

**Comment by rookie-luochao** [comment]
因为你的types里面有错误，可能你的json本身就不是特别满足规范，你可以自己检查一下，方便的话，可以把url或者openapi文件发我邮箱，我等会帮你看看

**Comment by nigiwen** [comment]
> 因为你的types里面有错误，可能你的json本身就不是特别满足规范，你可以自己检查一下，方便的话，可以把url或者openapi文件发我邮箱，我等会帮你看看

我用的示例 json

**Comment by rookie-luochao** [comment]
我刚想说你用的示例子，应该不会有问题，你换个这个示例试试呢？https://petstore3.swagger.io/api/v3/openapi.json

**Comment by rookie-luochao** [comment]
<img width="316" alt="image" src="https://github.com/openapi-ui/openapi-ts-request/assets/22948077/c9ba1120-9a49-48a8-8d99-e981c8b4e5d7">
我跑了很多测试用例都没问题，怎么你一个demo示例都跑不过😭

**Comment by rookie-luochao** [comment]
实在不行你可以用 `const { generateService } = require('openapi-ts-request')` 先试试，你方便的话到时候给我文件，我晚上回去用window import 测试下

**Comment by rookie-luochao** [comment]
请问后面换示例测试了吗，还有没有报错？

**Comment by nigiwen** [comment]
> 请问后面换示例测试了吗，还有没有报错？

没有报错，就是格式化一直失败，不知道什么原因

**Comment by rookie-luochao** [comment]
格式化不了，是调用prettier.write抛错了，我们捕获了错误并log出来，要看为什么prettier会报错，需要看下你的测试文件，我自己的项目也在用，也遇到过格式化出错的情况，一般还是文件内容有些问题（我们处理逻辑可能有没有考虑到的情况，导致文件内容有些问题），所以我说要你多搞几个openapi.json测试一下

**Comment by rookie-luochao** [comment]
请问你的问题解决了吗？使用其他的 openapi 文件还有没有问题，如果还有问题，你可以推你的代码到github上面，我帮你排查？

**Comment by rookie-luochao** [comment]
已经定位到问题，已经在 v0.3.3修复 https://www.npmjs.com/package/openapi-ts-request/v/0.3.3
等你验证反馈一下，如果解决了你的问题，我就关闭这个issue了
