### ISSUE TITLE
[BUG]枚举是纯数字时，生成的枚举有问题

### ISSUE THREAD

**Issue by luoyunchong** [openapi-ui/openapi-ts-request#51]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

- 在线的swagger json  中的ErrorCode 是纯数字时，生成的枚举命名不符合规范，无法使用
- https://[api.igeekfan.cn/swagger/base/swagger.json](https://api.igeekfan.cn/swagger/base/swagger.json)
-  ![image](https://github.com/user-attachments/assets/3d866b88-496b-4fb4-97fa-f6450c21454a)

- openapi-ts-request.config.ts
```
import type { GenerateServiceProps } from 'openapi-ts-request'

export default [
  {
    schemaPath: 'https://api.igeekfan.cn/swagger/base/swagger.json',
    serversPath: './src/api/Base',
    isDisplayTypeLabel: false,
    requestImportStatement: ``,
    namespace: 'Base',
    isCamelCase: false,
    hook: {
      customTypeName: (data: any) => {
        const { operationId } = data
        const funName = operationId ? operationId[0].toUpperCase() + operationId.substring(1) : ''
        const tag = data?.tags?.[0]

        return `${tag || ''}${funName}`
      },
    },
  },
] as GenerateServiceProps[]
```

### Expected Behavior

- 正确生成数字的枚举值

### Steps To Reproduce

- 可使用线上的swagger json进行测试

### Environment

```markdown
- OS:Windows 11
```

**Comment by rookie-luochao** [comment]
好的，我测试一下，请问这种情况你想生成什么样的枚举格式结果呢

**Comment by luoyunchong** [comment]
我觉得可以加一个前缀，避免编译问题，用户依旧可以使用枚举，具体前缀怎么写 大佬决定
```cs
export enum ErrorCode {
   X_100 = 100
}
```

**Comment by rookie-luochao** [comment]
```
export enum ErrorCode {
  INT_0 = 0,
  INT_999 = 999,
  INT_1000 = 1000,
  INT_1007 = 1007,
  INT_9999 = 9999,
  INT_10000 = 10000,
  INT_10001 = 10001,
  INT_10020 = 10020,
  INT_10030 = 10030,
  INT_10040 = 10040,
  INT_10050 = 10050,
  INT_10060 = 10060,
  INT_10070 = 10070,
  INT_10100 = 10100,
  INT_10140 = 10140,
}

export type IErrorCode = keyof typeof ErrorCode;

export function displayErrorCodeEnum(field: API.IErrorCode) {
  return {
    INT_0: 0,
    INT_999: 999,
    INT_1000: 1000,
    INT_1007: 1007,
    INT_9999: 9999,
    INT_10000: 10000,
    INT_10001: 10001,
    INT_10020: 10020,
    INT_10030: 10030,
    INT_10040: 10040,
    INT_10050: 10050,
    INT_10060: 10060,
    INT_10070: 10070,
    INT_10100: 10100,
    INT_10140: 10140,
  }[field];
}
```

请问这样可以满足你的需求吗？

**Comment by rookie-luochao** [comment]
想了一下，js里面对数字的抽象一般都是number, 故而前缀取名为 `NUMBER_`，已经在 #52 修复

**Comment by rookie-luochao** [comment]
请重新下载最新的 openapi-ts-request 包
```bash
npm i openapi-ts-request@latest --save-dev

 pnpm i openapi-ts-request@latest -D
```

**Comment by MaZhaolin** [comment]
<img width="833" alt="image" src="https://github.com/user-attachments/assets/c79f58d7-c6a7-4740-be9e-bb205b30fd8a">
使用最新的0.6版本出现了同样的问题

**Comment by rookie-luochao** [comment]
> <img alt="image" width="833" src="https://private-user-images.bgithub.xyz/13713662/372310615-c79f58d7-c6a7-4740-be9e-bb205b30fd8a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc3NTM5NTcsIm5iZiI6MTcyNzc1MzY1NywicGF0aCI6Ii8xMzcxMzY2Mi8zNzIzMTA2MTUtYzc5ZjU4ZDctYzZhNy00NzQwLWJlOWUtYmIyMDViMzBmZDhhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAxVDAzMzQxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQwYjJkMmRiYjI1NGFhNzA0OGQ1NGI5ODcyOTM2OTcyOWI5MWQ4MjBkYzQ4NDJkZWY5MjkwZTlkN2NiMGMwNTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.eMFvQWhYueynkTMWWRvIqd8cjegTa9Ovjgdeyl8dfMk"> 使用最新的0.6版本出现了同样的问题

可以邮箱发我一openapi.json定义吗

**Comment by Roading** [comment]
我这边也发现还存在这个问题

**Comment by rookie-luochao** [comment]
> 我这边也发现还存在这个问题

方便往我的邮箱 1055120207@qq.com 提供一份 openapi.json 定义吗？我来定位和解决你的问题

**Comment by qixm-burnish** [comment]
@rookie-luochao 已发送，在生成的`displayEnumLabel.ts`即可看见生成的枚举类型

**Comment by Roading** [comment]
@rookie-luochao 已发送，在生成的displayEnumLabel.ts即可看见生成的枚举类型

**Comment by rookie-luochao** [comment]
> @rookie-luochao 已发送，在生成的displayEnumLabel.ts即可看见生成的枚举类型

修复完成后，会在这条 issue 通知你

**Comment by rookie-luochao** [comment]
> @rookie-luochao 已发送，在生成的displayEnumLabel.ts即可看见生成的枚举类型

已经在 [v0.12.1](https://github.com/openapi-ui/openapi-ts-request/releases/tag/v0.12.1) 修复，如果解决了你的问题，帮忙点个✨支持一下，谢谢啦

**Comment by Roading** [comment]
你好，我看了下你修改的内容，是判断的是否为全数字。我觉得如果单独封装一个函数，格式化为合法key更合适一点（非法字符或以数值开头）。适用范围更广一点，防止有些带入空格等不正常内容

**Comment by Roading** [comment]
以数值开头的key，直接以下划线开头更简洁一点

**Comment by rookie-luochao** [comment]
> 你好，我看了下你修改的内容，是判断的是否为全数字。我觉得如果单独封装一个函数，格式化为合法key更合适一点（非法字符或以数值开头）。适用范围更广一点，防止有些带入空格等不正常内容

欢迎提个pr吧？[我的改动范围你看得到](https://github.com/openapi-ui/openapi-ts-request/blob/main/src/generator/serviceGenarator.ts#L983)
