### ISSUE TITLE
支持 yaml 文件吗

### ISSUE THREAD

**Issue by qhh001** [openapi-ui/openapi-ts-request#56]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by rookie-luochao** [comment]
就冲你这句话，今天晚上就支持

**Comment by rookie-luochao** [comment]
晚上写完了给你发通知😁😁😁

**Comment by rookie-luochao** [comment]
已经支持解析yaml文件，commit请查看：[feat: support parse swagger.yml/openapi.yml](https://github.com/openapi-ui/openapi-ts-request/commit/3f89463ba83421e690454051d528a50825460932)

**Comment by rookie-luochao** [comment]
可以使用了说一声哈，有bug麻烦继续反馈，我修复

**Comment by rookie-luochao** [comment]
使用下面的命令可以快速测试：
```bash
pnpm --package=openapi-ts-request@latest dlx openapi -i https://petstore3.swagger.io/api/v3/openapi.yaml -o ./apis
```

**Comment by qhh001** [comment]
> 使用下面的命令可以快速测试：
> 
> ```shell
> pnpm --package=openapi-ts-request@latest dlx openapi -i https://petstore3.swagger.io/api/v3/openapi.yaml -o ./apis
> ```

好的，我尽快测试一下。感谢能这么快速的反馈

**Comment by rookie-luochao** [comment]
> > 使用下面的命令可以快速测试：
> > ```shell
> > pnpm --package=openapi-ts-request@latest dlx openapi -i https://petstore3.swagger.io/api/v3/openapi.yaml -o ./apis
> > ```
> 
> 好的，我尽快测试一下。感谢能这么快速的反馈

不客气，把那个https链接换成你们自己的http地址，或者相对路径都是可以的，相对路径是以执行命令所在目录作为基准的

**Comment by rookie-luochao** [comment]
有其他优化也欢迎提出改进意见，有帮助到你麻烦动用小手点个小星星star

**Comment by qhh001** [comment]
可以的，yaml 文件已经支持了

**Comment by qhh001** [comment]
> > > 使用下面的命令可以快速测试：
> > > ```shell
> > > pnpm --package=openapi-ts-request@latest dlx openapi -i https://petstore3.swagger.io/api/v3/openapi.yaml -o ./apis
> > > ```
> > 
> > 
> > 好的，我尽快测试一下。感谢能这么快速的反馈
> 
> 不客气，把那个https链接换成你们自己的http地址，或者相对路径都是可以的，相对路径是以执行命令所在目录作为基准的

感谢感谢

**Comment by rookie-luochao** [comment]
欢迎后续反馈，我会快速响应，最近也还在考虑加一些功能
