### ISSUE TITLE
schemaPath必须是文件地址吗？

### ISSUE THREAD

**Issue by qhh001** [openapi-ui/openapi-ts-request#71]
1.
现在我们通过接口地址拿到批量的 yaml 文件的内容。可否直接将文件内容传给openapi-ts-request，或者是通过 node 的形式去调用openapi-ts-request的方法，将配置当成函数参数去执行。
2.例如
![image](https://github.com/user-attachments/assets/139d4958-9266-4600-9bd2-e41b1be6b32a)
接口给的是这个 yaml的string内容。
想通过 方法的形式去调用之类的

**Comment by rookie-luochao** [comment]
如果有这个功能诉求，可以支持

**Comment by rookie-luochao** [comment]
是找到什么新的解决办法了吗

**Comment by qhh001** [comment]
> 是找到什么新的解决办法了吗

![image](https://github.com/user-attachments/assets/c092ecae-bffd-4e07-9e38-252f2bc9ed0f)
是的。因为我是调用你的generateService这个方法么。然后通过 fs 模块生产一个临时的文件地址，用完之后再删除。循环掉 openapi 的生成

**Comment by qhh001** [comment]
毕竟我这边的需求是对接后端接口，不是固定的更新 yaml 文件的

**Comment by rookie-luochao** [comment]
嗯嗯，完全可以的，先用后端接口拿到配置内容，再写到文件里面去，然后schemapath用文件路径

**Comment by rookie-luochao** [comment]
好的，有问题或者功能请求可以继续提issue交流😁😁😁
