### ISSUE TITLE
导出的函数接口是否可以具名导出？

### ISSUE THREAD

**Issue by qhh001** [openapi-ui/openapi-ts-request#72]
**Is your feature request related to a problem? Please describe.**
现在这种批量的导出，应该是无法进行 treeshakeing。
![image](https://github.com/user-attachments/assets/bec08d83-3853-48fa-be23-ee9b8a8034f4)
**Describe the solution you'd like**
希望能够将生成的接口进行具名导出。

**Comment by qhh001** [comment]
![image](https://github.com/user-attachments/assets/8d4d0a88-b3ff-485b-a73a-57375710bbdc)
![image](https://github.com/user-attachments/assets/f1cf6269-b714-48b4-8e2b-5da94a6addbb)
希望能够得到如上图这种导出

**Comment by rookie-luochao** [comment]
你希望在统一的 index.ts 在进行一次具名导出？不用default吗，现在你其实可以直接使用 `import { list, create } from 'controllerToDubboService'`，而非 `import { list, create } from 'index.ts'`

**Comment by rookie-luochao** [comment]
以我的认知，应该不影响treeShaking，你有测试过，如果你只引入一个函数，其他无关函数都被打包进去了吗？

**Comment by qhh001** [comment]
> 你希望在统一的 index.ts 在进行一次具名导出？不用default吗，现在你其实可以直接使用 `import { list, create } from 'controllerToDubboService'`，而非 `import { list, create } from 'index.ts'`

其实是希望能有具名导出，然后使用的时候直接在一个大的index 直接引用，而不需要知道这个函数是具体在哪个文件夹中。类似于import { getAlertCenterPage } from '@/services'这种。实际上 services 下面还有很多文件或者文件夹。只要我的services 种的 index 里面导出了

**Comment by rookie-luochao** [comment]
现在其实是有 ast 提示的，你只要输入首字母就可以提示你哪个接口在哪里路径下，你说的这个问题我收到了哈，我最近测试下treeshaking和 从 index引入的 ast 提示

**Comment by qhh001** [comment]
> 现在其实是有 ast 提示的，你只要输入首字母就可以提示你哪个接口在哪里路径下，你说的这个问题我收到了哈，我最近测试下treeshaking和 从 index引入的 ast 提示，来达到你说的这个效果

好的。感谢

**Comment by rookie-luochao** [comment]
已经在 [v0.8.0](https://github.com/openapi-ui/openapi-ts-request/releases/tag/v0.8.0) 调整了导出结构，但是这样带来的一个可能产生的 bug 就是 index 暴漏了太多的东西，如果不同文件之间有重名的导出，可能就会遇到 ast 自动引入的结果不对，比如 a.ts、b.ts 文件都导出了 create, 可能 ast 自动提示 create 会只显示 a.ts 的导出，原先的导出方式则不会有这个风险，望悉知，你升级一下帮忙再反馈一下解决了你的问题没有

**Comment by qhh001** [comment]
> ，如果不同文件之间有重名的导出，可能就会遇到 ast 自动引入的结果不对

确实是有这个问题。我也测试了一下，现在是将 index 的 export default 改成了 export。这样的话我在使用的时候是可以将不同的文件当作一个 namespace 使用了。例如
```javascript
//index 文件
import * as login from './login';
export {
  login
};
``` 

```javascript
//pages 文件使用 api.
import {login} from '@/apis/app';
import { getAllowLoginWay } from '@/apis/app/login';

  const aaa=()=>{
    console.log(login.getAllowLoginWay);
    getAllowLoginWay()
  }
``` 
使用形式也有这两种.升级之后
![image](https://github.com/user-attachments/assets/460a474a-f43c-4d92-afc8-965a3056d892)
ast 的提示也会提示出来两个不同地方的引入

**Comment by rookie-luochao** [comment]
能提示从两个地方引入是正常的，你确实有重名的，就怕enterpriseEw 的 index 入口，暴漏重名的函数

**Comment by qhh001** [comment]
![image](https://github.com/user-attachments/assets/8b8636a5-ae3f-47bc-af66-50ac4d64ccaf)
现在这两个 index 完全一模一样。ast 也确实提示getAllowLoginWay有四个地方的导出。这个我理解是正常的。如果是做一个收口的导出文件确实是有冲突的问题。

**Comment by rookie-luochao** [comment]
加我vx: 1055120207 沟通

**Comment by qhh001** [comment]
回顾这个问题的过程。我理解 一个yaml 文件中不同的 tag 下面可能会有定义重名的函数。确实这种具名导出的话，会有冲突。

但是严格的openapi 的规范下同一个 yaml 文件中的operationId应该是唯一的。
